language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip
install:
  - go get github.com/olekukonko/tablewriter
  - go get gopkg.in/alecthomas/kingpin.v2
  - go get gopkg.in/yaml.v2
script: go build download-geofabrik
