language: go

go:
  - "1.9"
  - "1.10"
  - master

# use gox
#env:
#  - GIMME_OS=linux GIMME_ARCH=386 GIMME_DEBUG=1 GIMME_TYPE=source
#  - GIMME_OS=linux GIMME_ARCH=amd64 GIMME_DEBUG=1 GIMME_TYPE=source
#  - GIMME_OS=darwin GIMME_ARCH=386 GIMME_DEBUG=1 GIMME_TYPE=source
#  - GIMME_OS=darwin GIMME_ARCH=amd64 GIMME_DEBUG=1 GIMME_TYPE=source
#  - GIMME_OS=windows GIMME_ARCH=386 GIMME_DEBUG=1 GIMME_TYPE=source
#  - GIMME_OS=windows GIMME_ARCH=amd64 GIMME_DEBUG=1 GIMME_TYPE=source
#  #- GIMME_OS=linux GIMME_ARCH=arm

install:
  #- go get -u github.com/golang/lint/golint
  #- go install -u github.com/golang/lint/golint
  - go get -v github.com/mitchellh/gox
  - go get -t -v ./...

# Use Makefile
#script:
#  - golint -min_confidence=0.8 ./...
#  - go build -v ./...
